<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container58ccbce\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container58ccbce/appProdProjectContainer.php') {
    touch(__DIR__.'/Container58ccbce.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container58ccbce\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container58ccbce\appProdProjectContainer([
    'container.build_hash' => '58ccbce',
    'container.build_id' => '7fce3095',
    'container.build_time' => 1661801855,
], __DIR__.\DIRECTORY_SEPARATOR.'Container58ccbce');
